default:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 16
      account: UG50399
      user: sowflakeyuvaraj
      database: raw
      warehouse: transforming
      schema: dbt_bhipple
      password: 52AYmKF2KTjgwiR
      role: transformer
